// <auto-generated />
namespace Proj7_grad_tomasello.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changedtheresultval : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedtheresultval));
        
        string IMigrationMetadata.Id
        {
            get { return "201811262152119_Changed the result val"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
